{
    'name': 'M02_P0201_TRAVEL_REQUEST',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Module for managing travel requests and expenses',
    'author': 'PSM',
    'depends': ['base', 'mail', 'hr', 'hr_expense', 'approvals', 'M02_P0200'],
    'data': [
        'security/ir.model.access.csv',
        'security/x_psm_travel_request_security.xml',
        'data/travel_data.xml',
        'data/travel_demo_data.xml',
        'data/travel_zone_data.xml',
        'views/view_psm_travel_zone.xml',
        'views/view_psm_travel_admin_config.xml',
        'views/view_psm_travel_detail_config.xml',
        'views/view_psm_travel_destination.xml',
        'views/view_psm_travel_hotel.xml',
        'views/view_psm_travel_request.xml',
        'views/view_psm_approval_request.xml',
        'views/view_psm_hr_expense.xml',
        'report/view_psm_travel_report.xml',
        'views/view_psm_menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'OPL-1',
}
