# -*- coding: utf-8 -*-
{
    "name": "M02_P0501_STORE_PACKAGE",
    "version": "1.0",
    "category": "Project",
    "summary": "Demo store package seed data for P0501",
    "description": """
        Seed data module for the P0501 store package happy path.
    """,
    "author": "PSM",
    "depends": [
        "mail",
        "project",
        "hr_timesheet",
        "crm",
        "documents",
        "documents_project",
        "project_account_budget",
        "account",
        "account_reports",
        "approvals",
        "survey",
        "M02_P0200",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/project_project_stage_data.xml",
        "data/project_task_type_data.xml",
        "data/survey_template_data.xml",
        "data/approval_category_data.xml",
        "data/project_project_data.xml",
        "data/project_task_data.xml",
        "views/project_project_views.xml",
        "views/project_task_views.xml",
        "views/documents_views.xml",
        "views/approval_request_views.xml",
        "views/survey_views.xml",
        "views/menus.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
