{
    'name': 'M02_P0211 Onboarding OPS',
    'version': '1.0',
    'summary': '',
    'category': 'Human Resources',
    'author': 'PSM',
    'license': 'LGPL-3',
    'depends': [
        'base', 
        'portal', 
        'mail', 
        'hr', 
        'hr_recruitment', 
        'base_automation', 
        'survey', 
        'appointment', 
        'sign', 
        'hr_sign',
        'auth_signup',
        'M02_P0200',
        'portal_custom'
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/contract_templates.xml',
        'data/training_config_data.xml',
        'data/probation_config.xml',
        # 'data/mail_server_data.xml',
        'data/mail_templates.xml',
        'data/automated_actions.xml',
        'data/vsattp_survey_data.xml',
        'views/view_psm_res_partner.xml',
        'views/view_psm_hr_applicant.xml',
        'views/view_psm_hr_employee.xml',
        'views/view_psm_mail_activity_schedule_ext.xml',
        'views/portal_templates.xml',
        'views/view_psm_hr_training_config.xml',
        'views/view_psm_hr_adecco_config.xml',
        'views/view_psm_hr_report.xml',
        'wizard/hr_probation_wizard_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'M02_P0211/static/src/js/portal_onboarding.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': True,
}
