from . import x_psm_hr_onboarding_task
from . import x_psm_hr_adecco_config
from . import res_partner
from . import hr_applicant
from . import hr_employee_ext
from . import sign_request_ext
from . import mail_activity_schedule_ext
from . import survey_invite_ext
from . import x_psm_hr_training_config
from . import mail_activity
